title: Vinoda Varshini Rajagopal
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vinodavarshini-r">LinkedIn</a> |
  <a href="https://github.com/VinodaVarshini">GitHub</a>
 
  <br>  
  I'm working on Data Science, Machine learning & NLP related problems.
  Working in Cards domain for 5 years.
  <br>
  </p>

theme: jekyll-theme-minimal

