title: Vinoda Varshini Rajagopal
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vinodavarshini-r">LinkedIn</a> |
  <a href="https://github.com/VinodaVarshini">GitHub</a>
 
  <br>  
  I'm working on Data Science, Machine learning & NLP related problems.
  Working in Cards domain for 5 years.
  <br>
  </p>
  
  # MachineLearningUsingPython
![image.jpg](image/ml_top.jpg)<br><br>
Machine Learning is the study of Computer Algorithms that allow computer programs to automatically improve through experience.
Machine Learning Algorithms use statistics to find patterns in massive amounts of data, such as numbers, words, images. 
These data are fed into machine learning algorithm, and, computer learns through this algorithm to provide better predictions in the future.

## Repository Overview
This repository contains different Machine Learning Algorithm.

## Table of Contents
- [European Premier League Predictions](#section1)<br>
- [Grocery Store Recommendation](#section2)<br>
- [Loan Sanction Amount Prediction](#section3)<br>

___
<a id=section1></a>
### [European Premier League Predictions](./EuropeanPremierLeaguePredictions)
![image.jpg](image/football.jpeg)<br>.
- EPL games played between teams as __Home Team and Away Team__ in which classification algorithm is applied to predict the result.
- Model which is built to Predict the winning team in European Premier League.
- [Link for Jupyter notebook](./EuropeanPremierLeaguePredictions/EuropeanPremierLeague_Predictions.ipynb)

___
<a id=section2></a>
### [Grocery Store Recommendation](./GroceryStoreRecommendation)
![image.jpg](image/groceryimg.jpg)<br>
- Building recommendation system that helps customer for purchasing in a Grocery Store.
- Helps in increasing the purchase pattern and increasing the profit for the store.
- Recommendation system built using __Apriori Algorithm__. 
- [Link for Jupyter notebook](./GroceryStoreRecommendation/RecommendationSystem_GroceryStore.ipynb)

___
<a id=section3></a>
### [Loan Sanction Amount Prediction](./LoanSanctionPrediction)

- Performed EDA on loan data.
- Predicted loan sanction amount with __Regression model__.
- [Link for Jupyter notebook](./LoanSanctionPrediction)

theme: jekyll-theme-minimal

